#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOTEBOOK_PATH="${ROOT_DIR}/hyper_optimized_ft_snn_100_experiments.ipynb"
WAIT_FOR_COMPLETION=false

if [[ "${1:-}" == "--wait" ]]; then
  WAIT_FOR_COMPLETION=true
elif [[ "${1:-}" != "" ]]; then
  echo "Usage: $0 [--wait]" >&2
  exit 1
fi

if [[ ! -f "${NOTEBOOK_PATH}" ]]; then
  echo "Notebook not found: ${NOTEBOOK_PATH}" >&2
  exit 1
fi

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
RUN_ROOT="${ROOT_DIR}/parallel_runs/${TIMESTAMP}"
LOG_DIR="${RUN_ROOT}/logs"
OUT_NOTEBOOK_DIR="${RUN_ROOT}/executed_notebooks"
mkdir -p "${LOG_DIR}" "${OUT_NOTEBOOK_DIR}"
GENERATED_SCRIPT="${RUN_ROOT}/notebook_exec_source.py"

python - "${NOTEBOOK_PATH}" "${GENERATED_SCRIPT}" <<'PY'
import json
import pathlib
import sys

notebook_path = pathlib.Path(sys.argv[1])
script_path = pathlib.Path(sys.argv[2])
nb = json.loads(notebook_path.read_text(encoding="utf-8"))
chunks = []
chunks.append("# Auto-generated from notebook code cells.\n")
chunks.append("# Generated by run_6_variations_parallel.sh\n\n")
for cell in nb.get("cells", []):
    if cell.get("cell_type") != "code":
        continue
    chunks.append("# ===== Notebook Code Cell =====\n")
    source_lines = cell.get("source", [])
    if source_lines and not source_lines[-1].endswith("\n"):
        source_lines[-1] = source_lines[-1] + "\n"
    chunks.extend(source_lines)
    chunks.append("\n")
script_path.write_text("".join(chunks), encoding="utf-8")
PY

declare -a TAGS=("Base" "VI" "VII" "VIII" "VIV" "VV")
# Two jobs per GPU across 3 GPUs.
declare -a GPUS=("0" "1" "2" "0" "1" "2")

PID_FILE="${RUN_ROOT}/pids.tsv"
printf "pid\ttag\tgpu\tlog\n" > "${PID_FILE}"

launch_run() {
  local tag="$1"
  local gpu="$2"
  local log_path="$3"

  # Keep the worker alive across SSH disconnects by detaching it from the
  # caller's terminal and ignoring SIGHUP.
  nohup env \
    PYTHONUNBUFFERED=1 \
    CUDA_VISIBLE_DEVICES="${gpu}" \
    CUDA_DEVICE_INDICES="0" \
    PREFERRED_GPU_INDEX="0" \
    EXPERIMENT_TAG="${tag}" \
    DEVICE_OVERRIDE="auto" \
    ROOT_DIR="${ROOT_DIR}" \
    GENERATED_SCRIPT="${GENERATED_SCRIPT}" \
    bash -c '
      cd "${ROOT_DIR}"
      exec python "${GENERATED_SCRIPT}"
    ' > "${log_path}" 2>&1 < /dev/null &
  LAUNCHED_PID="$!"
}

echo "Launching 6 notebook runs in detached background processes..."
for i in "${!TAGS[@]}"; do
  tag="${TAGS[$i]}"
  gpu="${GPUS[$i]}"
  log_path="${LOG_DIR}/${tag}.log"
  out_notebook="${tag}_executed.ipynb"

  launch_run "${tag}" "${gpu}" "${log_path}"
  pid="${LAUNCHED_PID}"
  printf "%s\t%s\t%s\t%s\n" "${pid}" "${tag}" "${gpu}" "${log_path}" >> "${PID_FILE}"
  echo "  started tag=${tag} gpu=${gpu} pid=${pid}"
done

echo
echo "Run directory: ${RUN_ROOT}"
echo "PID file: ${PID_FILE}"
echo "Watch logs: tail -f ${LOG_DIR}/*.log"
echo "Check processes: ps -fp \$(cut -f1 ${PID_FILE} | tail -n +2 | tr '\n' ' ')"
echo "SSH-safe: launched workers use nohup and will keep running after disconnect."

if [[ "${WAIT_FOR_COMPLETION}" == "true" ]]; then
  echo
  echo "Waiting for all runs to finish..."
  echo "If this shell disconnects, the monitor stops but the launched runs keep going."
  STATUS_UPDATE_SECONDS="${STATUS_UPDATE_SECONDS:-20}"
  FAILED_RUNS=0
  TOTAL_RUNS="${#TAGS[@]}"
  COMPLETED_RUNS=0
  NEXT_STATUS_TS=0

  declare -A PID_TAG
  declare -A PID_GPU
  declare -A PID_LOG
  declare -A PID_DONE

  while IFS=$'\t' read -r pid tag gpu log_path; do
    if [[ "${pid}" == "pid" ]]; then
      continue
    fi
    PID_TAG["${pid}"]="${tag}"
    PID_GPU["${pid}"]="${gpu}"
    PID_LOG["${pid}"]="${log_path}"
    PID_DONE["${pid}"]=0
  done < "${PID_FILE}"

  detach_monitor_on_interrupt() {
    echo
    echo "Interrupt received; leaving launched runs active and stopping only this monitor."
    echo "Run directory: ${RUN_ROOT}"
    echo "PID file: ${PID_FILE}"
    echo "Watch logs later with: tail -f ${LOG_DIR}/*.log"
    echo "Check processes with: ps -fp \$(cut -f1 ${PID_FILE} | tail -n +2 | tr '\n' ' ')"
    exit 130
  }
  trap detach_monitor_on_interrupt INT TERM

  print_status_snapshot() {
    local running_count=0
    local now_human
    now_human="$(date '+%Y-%m-%d %H:%M:%S')"
    for pid in "${!PID_DONE[@]}"; do
      if [[ "${PID_DONE[${pid}]}" -eq 0 ]]; then
        running_count=$((running_count + 1))
      fi
    done

    echo
    echo "[${now_human}] progress: completed=${COMPLETED_RUNS}/${TOTAL_RUNS} running=${running_count} failed=${FAILED_RUNS}"
    while IFS=$'\t' read -r pid tag gpu log_path; do
      if [[ "${pid}" == "pid" ]]; then
        continue
      fi
      if [[ "${PID_DONE[${pid}]}" -eq 1 ]]; then
        continue
      fi

      latest_line="$(tail -n 60 "${log_path}" 2>/dev/null | tr '\r' '\n' | sed -E 's/\x1b\[[0-9;]*[[:alpha:]]//g' | awk 'NF{line=$0} END{print line}')"
      if [[ -z "${latest_line}" ]]; then
        latest_line="(no output yet)"
      fi
      latest_line="${latest_line:0:180}"
      echo "  [${tag}|gpu=${gpu}|pid=${pid}] ${latest_line}"
    done < "${PID_FILE}"
  }

  while [[ "${COMPLETED_RUNS}" -lt "${TOTAL_RUNS}" ]]; do
    for pid in "${!PID_DONE[@]}"; do
      if [[ "${PID_DONE[${pid}]}" -eq 1 ]]; then
        continue
      fi
      if kill -0 "${pid}" 2>/dev/null; then
        continue
      fi

      if wait "${pid}"; then
        status_code=0
      else
        status_code=$?
      fi

      PID_DONE["${pid}"]=1
      COMPLETED_RUNS=$((COMPLETED_RUNS + 1))
      if [[ "${status_code}" -ne 0 ]]; then
        FAILED_RUNS=$((FAILED_RUNS + 1))
      fi
      echo "  completed tag=${PID_TAG[${pid}]} gpu=${PID_GPU[${pid}]} pid=${pid} status=${status_code} (log: ${PID_LOG[${pid}]})"
    done

    current_ts="$(date +%s)"
    if [[ "${current_ts}" -ge "${NEXT_STATUS_TS}" ]]; then
      print_status_snapshot
      NEXT_STATUS_TS=$((current_ts + STATUS_UPDATE_SECONDS))
    fi

    sleep 2
  done

  trap - INT TERM

  if [[ "${FAILED_RUNS}" -gt 0 ]]; then
    echo "Finished with failures: ${FAILED_RUNS} run(s) failed."
    exit 1
  fi

  echo "Finished successfully: all 6 runs completed."
fi
